import { normalizeGuess } from "./guess.js";
import {
  CustomThemeInputBaseSchema,
  type CustomThemeInput,
  type ThemeMetadata,
} from "./schemas.js";
import { VALIDATION_LIMITS } from "./constants.js";

export type PresetTheme = {
  metadata: ThemeMetadata;
  words: readonly string[];
};

const general = [
  "airplane",
  "alarm clock",
  "anchor",
  "backpack",
  "balloon",
  "basket",
  "bathtub",
  "bicycle",
  "binoculars",
  "book",
  "bridge",
  "broom",
  "bucket",
  "camera",
  "candle",
  "castle",
  "chair",
  "cloud",
  "compass",
  "computer",
  "crown",
  "diamond",
  "door",
  "drum",
  "envelope",
  "factory",
  "feather",
  "fire hydrant",
  "fireplace",
  "flashlight",
  "flower",
  "fountain",
  "gift",
  "globe",
  "hammer",
  "hat",
  "headphones",
  "helicopter",
  "hourglass",
  "house",
  "island",
  "key",
  "kite",
  "ladder",
  "lamp",
  "lighthouse",
  "magnet",
  "mailbox",
  "map",
  "microphone",
  "moon",
  "motorcycle",
  "mountain",
  "mug",
  "newspaper",
  "paintbrush",
  "pencil",
  "piano",
  "pirate ship",
  "rainbow",
  "robot",
  "rocket",
  "roller coaster",
  "sailboat",
  "sandcastle",
  "satellite",
  "scissors",
  "shield",
  "shoe",
  "skateboard",
  "snowman",
  "spaceship",
  "spoon",
  "staircase",
  "star",
  "statue",
  "stop sign",
  "suitcase",
  "sun",
  "sunglasses",
  "sword",
  "table",
  "telescope",
  "tent",
  "toothbrush",
  "traffic light",
  "train",
  "treasure chest",
  "tree",
  "trophy",
  "truck",
  "umbrella",
  "volcano",
  "watch",
  "waterfall",
  "wheelbarrow",
  "windmill",
  "window",
  "wrench",
  "yo-yo",
  "zipper",
  "campfire",
  "crystal ball",
  "dream",
  "earthquake",
  "footprint",
  "maze",
  "shadow",
  "snowflake",
  "telephone",
  "vacuum cleaner",
] as const;

const animals = [
  "alligator",
  "alpaca",
  "ant",
  "anteater",
  "armadillo",
  "baboon",
  "badger",
  "bat",
  "bear",
  "beaver",
  "bee",
  "beetle",
  "bison",
  "butterfly",
  "camel",
  "capybara",
  "cat",
  "caterpillar",
  "chameleon",
  "cheetah",
  "chicken",
  "chimpanzee",
  "cobra",
  "cockatoo",
  "cow",
  "coyote",
  "crab",
  "crocodile",
  "crow",
  "deer",
  "dog",
  "dolphin",
  "donkey",
  "dragonfly",
  "duck",
  "eagle",
  "eel",
  "elephant",
  "falcon",
  "ferret",
  "flamingo",
  "fly",
  "fox",
  "frog",
  "gazelle",
  "gecko",
  "giraffe",
  "goat",
  "goose",
  "gorilla",
  "grasshopper",
  "hamster",
  "hedgehog",
  "hippopotamus",
  "horse",
  "hummingbird",
  "hyena",
  "iguana",
  "jaguar",
  "jellyfish",
  "kangaroo",
  "koala",
  "ladybug",
  "lemur",
  "leopard",
  "lion",
  "llama",
  "lobster",
  "manatee",
  "meerkat",
  "monkey",
  "moose",
  "mosquito",
  "moth",
  "mouse",
  "octopus",
  "orangutan",
  "ostrich",
  "otter",
  "owl",
  "panda",
  "parrot",
  "peacock",
  "pelican",
  "penguin",
  "pig",
  "platypus",
  "polar bear",
  "porcupine",
  "rabbit",
  "raccoon",
  "ram",
  "rat",
  "rhinoceros",
  "rooster",
  "scorpion",
  "seahorse",
  "seal",
  "shark",
  "sheep",
  "skunk",
  "sloth",
  "snail",
  "snake",
  "spider",
  "squid",
  "squirrel",
  "starfish",
  "stingray",
  "swan",
  "tiger",
  "toucan",
  "turtle",
  "walrus",
  "whale",
  "wolf",
  "wombat",
  "woodpecker",
  "zebra",
] as const;

const food = [
  "apple",
  "avocado",
  "bagel",
  "banana",
  "barbecue",
  "birthday cake",
  "blueberry",
  "bread",
  "broccoli",
  "brownie",
  "burrito",
  "butter",
  "cabbage",
  "candy",
  "carrot",
  "cheeseburger",
  "cheesecake",
  "cherry",
  "chicken wings",
  "chocolate",
  "cinnamon roll",
  "coconut",
  "cookie",
  "corn",
  "cotton candy",
  "croissant",
  "cupcake",
  "curry",
  "doughnut",
  "dumpling",
  "egg",
  "eggplant",
  "falafel",
  "fish and chips",
  "french fries",
  "fried chicken",
  "garlic",
  "gingerbread house",
  "grapes",
  "grilled cheese",
  "guacamole",
  "hamburger",
  "hot dog",
  "ice cream",
  "jam",
  "jelly beans",
  "kebab",
  "kiwi",
  "lasagna",
  "lemon",
  "lollipop",
  "macaroni",
  "mango",
  "marshmallow",
  "meatball",
  "milkshake",
  "muffin",
  "mushroom",
  "nachos",
  "noodles",
  "olive",
  "omelet",
  "onion",
  "orange",
  "pancakes",
  "papaya",
  "pasta",
  "peach",
  "peanut",
  "pear",
  "pepper",
  "pepperoni pizza",
  "pickle",
  "pie",
  "pineapple",
  "popcorn",
  "popsicle",
  "potato",
  "pretzel",
  "pumpkin",
  "ramen",
  "rice",
  "salad",
  "sandwich",
  "sausage",
  "shrimp",
  "smoothie",
  "soup",
  "spaghetti",
  "strawberry",
  "sushi",
  "taco",
  "toast",
  "tomato",
  "waffle",
  "watermelon",
  "yogurt",
  "bacon",
  "beans",
  "biscuit",
  "cereal",
  "churro",
  "cucumber",
  "fajitas",
  "fortune cookie",
  "fried egg",
  "honey",
  "lobster dinner",
  "mashed potatoes",
  "pudding",
  "roast turkey",
  "spring roll",
  "steak",
  "tortilla",
  "tuna",
  "whipped cream",
] as const;

const places = [
  "airport",
  "amusement park",
  "aquarium",
  "art gallery",
  "bakery",
  "bank",
  "barn",
  "beach",
  "bookstore",
  "bowling alley",
  "bus station",
  "cafe",
  "campground",
  "castle",
  "cathedral",
  "cave",
  "cemetery",
  "cinema",
  "circus",
  "city hall",
  "classroom",
  "clothing store",
  "construction site",
  "courthouse",
  "desert",
  "diner",
  "farm",
  "fire station",
  "flower shop",
  "forest",
  "gas station",
  "glacier",
  "grocery store",
  "gym",
  "harbor",
  "hospital",
  "hotel",
  "ice rink",
  "island",
  "jungle",
  "kindergarten",
  "laboratory",
  "lake",
  "laundromat",
  "library",
  "lighthouse",
  "market",
  "museum",
  "nightclub",
  "office",
  "opera house",
  "orchard",
  "palace",
  "parking lot",
  "pet shop",
  "pharmacy",
  "playground",
  "police station",
  "post office",
  "prison",
  "rainforest",
  "restaurant",
  "river",
  "school",
  "shopping mall",
  "skate park",
  "ski resort",
  "stadium",
  "subway station",
  "supermarket",
  "swimming pool",
  "temple",
  "theater",
  "theme park",
  "train station",
  "university",
  "veterinary clinic",
  "volcano",
  "water park",
  "waterfall",
  "wedding chapel",
  "wind farm",
  "zoo",
  "Eiffel Tower",
  "Great Wall of China",
  "Grand Canyon",
  "Leaning Tower of Pisa",
  "Mount Everest",
  "Niagara Falls",
  "North Pole",
  "pyramid",
  "Statue of Liberty",
  "Stonehenge",
  "Sydney Opera House",
  "Taj Mahal",
  "Times Square",
  "Tower Bridge",
  "treehouse",
  "underwater city",
  "space station",
  "moon base",
  "haunted house",
  "pirate cove",
  "secret garden",
  "tree nursery",
  "rooftop",
  "volleyball court",
  "warehouse",
  "workshop",
  "canyon",
  "cliff",
  "dock",
  "meadow",
  "oasis",
  "pier",
  "swamp",
  "vineyard",
] as const;

const videoGameCharacters = [
  "Mario",
  "Luigi",
  "Princess Peach",
  "Bowser",
  "Yoshi",
  "Toad",
  "Donkey Kong",
  "Diddy Kong",
  "Link",
  "Princess Zelda",
  "Ganondorf",
  "Kirby",
  "Meta Knight",
  "King Dedede",
  "Pikachu",
  "Charizard",
  "Jigglypuff",
  "Mewtwo",
  "Lucario",
  "Sonic",
  "Tails",
  "Knuckles",
  "Doctor Eggman",
  "Shadow the Hedgehog",
  "Pac-Man",
  "Mega Man",
  "Crash Bandicoot",
  "Coco Bandicoot",
  "Spyro",
  "Duke Nukem",
  "Master Chief",
  "Cortana",
  "Kratos",
  "Atreus",
  "Nathan Drake",
  "Sackboy",
  "Ratchet",
  "Clank",
  "Aloy",
  "Ellie",
  "Joel Miller",
  "Solid Snake",
  "Cloud Strife",
  "Tifa Lockhart",
  "Sephiroth",
  "Chocobo",
  "Sora",
  "Riku",
  "Lara Croft",
  "Samus Aran",
  "Fox McCloud",
  "Captain Falcon",
  "Ness",
  "Inkling",
  "Isabelle",
  "Tom Nook",
  "Villager",
  "Steve",
  "Creeper",
  "Enderman",
  "Alex",
  "Geralt of Rivia",
  "Ciri",
  "Doom Slayer",
  "Gordon Freeman",
  "Chell",
  "GLaDOS",
  "Agent 47",
  "Ezio Auditore",
  "Altair",
  "Commander Shepard",
  "Jill Valentine",
  "Leon Kennedy",
  "Chris Redfield",
  "Arthur Morgan",
  "John Marston",
  "Trevor Philips",
  "CJ",
  "Scorpion",
  "Sub-Zero",
  "Raiden",
  "Chun-Li",
  "Ryu",
  "Ken Masters",
  "Liu Kang",
  "Tracer",
  "Winston",
  "DVa",
  "Mercy",
  "Reaper",
  "Jinx",
  "Teemo",
  "Ahri",
  "Poro",
  "Jonesy",
  "Peely",
  "Among Us Crewmate",
  "Fall Guy",
  "Cuphead",
  "Mugman",
  "Sans",
  "Papyrus",
  "Shovel Knight",
  "Hollow Knight",
  "Ori",
  "Rayman",
  "Earthworm Jim",
  "Guybrush Threepwood",
  "Guybrush",
  "Razputin",
  "Big Daddy",
  "Little Sister",
  "Vault Boy",
  "Pyramid Head",
  "Amaterasu",
  "Phoenix Wright",
  "Professor Layton",
  "Monokuma",
  "Bomberman",
  "Qbert",
] as const;

const music = [
  "Yellow Submarine",
  "Purple Rain",
  "Ring of Fire",
  "Firework",
  "Watermelon Sugar",
  "Eye of the Tiger",
  "Walking on Sunshine",
  "Dancing Queen",
  "Rocket Man",
  "Man in the Mirror",
  "Umbrella",
  "Pocketful of Sunshine",
  "Castle on the Hill",
  "Cake by the Ocean",
  "Counting Stars",
  "Blinding Lights",
  "Here Comes the Sun",
  "Lucy in the Sky with Diamonds",
  "Blackbird",
  "Octopus's Garden",
  "Piano Man",
  "Crocodile Rock",
  "Tiny Dancer",
  "Hungry Like the Wolf",
  "Rock Lobster",
  "Blue Moon",
  "Red Red Wine",
  "Pink Cadillac",
  "Brown Eyed Girl",
  "Black or White",
  "White Flag",
  "Green Light",
  "Golden",
  "Silver Springs",
  "Strawberry Fields Forever",
  "Banana Pancakes",
  "Cherry Pie",
  "Sugar Sugar",
  "Ice Cream",
  "Peaches",
  "Lollipop",
  "Waterfalls",
  "River",
  "Ocean Eyes",
  "Island in the Sun",
  "A Sky Full of Stars",
  "Drops of Jupiter",
  "Fly Me to the Moon",
  "Saturn",
  "Venus",
  "Starman",
  "Space Oddity",
  "Great Balls of Fire",
  "Burning Love",
  "Smoke on the Water",
  "Set Fire to the Rain",
  "Cold as Ice",
  "Ice Ice Baby",
  "Hot Stuff",
  "Heat Waves",
  "Thunder",
  "Lightning Crashes",
  "Snowman",
  "Sweater Weather",
  "November Rain",
  "Summer of 69",
  "Cruel Summer",
  "Autumn Leaves",
  "Winter Wonderland",
  "Daylight",
  "Midnight Sky",
  "Sunday Morning",
  "Friday I'm in Love",
  "Wake Me Up",
  "Good Morning",
  "Night Moves",
  "The Long and Winding Road",
  "Life Is a Highway",
  "Take Me Home Country Roads",
  "Boulevard of Broken Dreams",
  "Bicycle Race",
  "Fast Car",
  "Drive",
  "Big Yellow Taxi",
  "Last Train to London",
  "Leaving on a Jet Plane",
  "Sailing",
  "Row Row Row Your Boat",
  "Message in a Bottle",
  "Genie in a Bottle",
  "99 Red Balloons",
  "Paper Planes",
  "House of Cards",
  "Poker Face",
  "Telephone",
  "Video Killed the Radio Star",
  "Radioactive",
  "Electric Feel",
  "Digital Love",
  "Stereo Hearts",
  "Music Box",
  "The Sound of Silence",
  "Loud",
  "Whistle",
  "The Fox",
  "Who Let the Dogs Out",
  "Butterfly",
  "Fireflies",
  "Roar",
  "Dark Horse",
  "The Lion Sleeps Tonight",
  "Three Little Birds",
  "Rockin' Robin",
  "Hound Dog",
  "Cool for Cats",
  "Eye of the Needle",
  "Heart of Glass",
  "Achy Breaky Heart",
  "Broken Wings",
  "Wind Beneath My Wings",
] as const;

export const PRESET_THEMES = {
  general: {
    metadata: {
      id: "general",
      name: "General",
      description: "Everyday objects, nature, ideas, and familiar sights.",
      isCustom: false,
      wordCount: general.length,
    },
    words: general,
  },
  animals: {
    metadata: {
      id: "animals",
      name: "Animals",
      description: "Creatures from back gardens to the deep ocean.",
      isCustom: false,
      wordCount: animals.length,
    },
    words: animals,
  },
  food: {
    metadata: {
      id: "food",
      name: "Food",
      description: "Snacks, meals, fruit, desserts, and tasty ingredients.",
      isCustom: false,
      wordCount: food.length,
    },
    words: food,
  },
  places: {
    metadata: {
      id: "places",
      name: "Places",
      description: "Local landmarks, wild landscapes, and world-famous spots.",
      isCustom: false,
      wordCount: places.length,
    },
    words: places,
  },
  "video-game-characters": {
    metadata: {
      id: "video-game-characters",
      name: "Video Game Characters",
      description: "Iconic heroes, villains, mascots, and companions.",
      isCustom: false,
      wordCount: videoGameCharacters.length,
    },
    words: videoGameCharacters,
  },
  music: {
    metadata: {
      id: "music",
      name: "Songs & Music",
      description: "Highly drawable song titles from across the decades.",
      isCustom: false,
      wordCount: music.length,
    },
    words: music,
  },
} as const satisfies Record<string, PresetTheme>;

export type PresetThemeId = keyof typeof PRESET_THEMES;

export const THEME_METADATA: readonly ThemeMetadata[] = Object.values(
  PRESET_THEMES,
).map((theme) => theme.metadata);

export function isPresetThemeId(id: string): id is PresetThemeId {
  return Object.hasOwn(PRESET_THEMES, id);
}

export function getPresetTheme(id: string): PresetTheme | undefined {
  return isPresetThemeId(id) ? PRESET_THEMES[id] : undefined;
}

export type CustomThemeValidationIssue = {
  code:
    | "INVALID_STRUCTURE"
    | "TOO_FEW_UNIQUE_WORDS"
    | "TOO_MANY_UNIQUE_WORDS"
    | "DUPLICATE_WORD";
  message: string;
  path?: string;
};

export type CustomThemeValidationResult =
  | {
      success: true;
      data: CustomThemeInput;
    }
  | {
      success: false;
      issues: CustomThemeValidationIssue[];
    };

/**
 * Validates and cleans a locally-created theme. Uniqueness is evaluated with
 * the same Unicode normalization used for guesses, preventing answer aliases
 * such as "Crème brûlée" and "creme brulee" from appearing twice.
 */
export function validateCustomTheme(
  input: unknown,
): CustomThemeValidationResult {
  const parsed = CustomThemeInputBaseSchema.safeParse(input);
  if (!parsed.success) {
    return {
      success: false,
      issues: parsed.error.issues.map((issue) => ({
        code: "INVALID_STRUCTURE",
        message: issue.message,
        path: issue.path.join("."),
      })),
    };
  }

  const seen = new Map<string, string>();
  const uniqueWords: string[] = [];
  const duplicateWords: string[] = [];

  for (const rawWord of parsed.data.words) {
    const word = rawWord.trim().replace(/\s+/gu, " ");
    const normalized = normalizeGuess(word);
    if (seen.has(normalized)) {
      duplicateWords.push(word);
      continue;
    }
    seen.set(normalized, word);
    uniqueWords.push(word);
  }

  const issues: CustomThemeValidationIssue[] = [];
  if (duplicateWords.length > 0) {
    issues.push({
      code: "DUPLICATE_WORD",
      message: `Duplicate words after normalization: ${duplicateWords.join(", ")}`,
      path: "words",
    });
  }
  if (uniqueWords.length < VALIDATION_LIMITS.customThemeWords.min) {
    issues.push({
      code: "TOO_FEW_UNIQUE_WORDS",
      message: `A custom theme needs at least ${VALIDATION_LIMITS.customThemeWords.min} unique words.`,
      path: "words",
    });
  }
  if (uniqueWords.length > VALIDATION_LIMITS.customThemeWords.max) {
    issues.push({
      code: "TOO_MANY_UNIQUE_WORDS",
      message: `A custom theme can contain at most ${VALIDATION_LIMITS.customThemeWords.max} unique words.`,
      path: "words",
    });
  }

  if (issues.length > 0) {
    return { success: false, issues };
  }

  return {
    success: true,
    data: {
      ...(parsed.data.id === undefined ? {} : { id: parsed.data.id }),
      name: parsed.data.name.trim().replace(/\s+/gu, " "),
      words: uniqueWords,
    },
  };
}
